# Generated by Django 5.2.9 on 2025-12-22 11:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Full name of the candidate', max_length=255)),
                ('email', models.EmailField(help_text='Unique email address of the candidate', max_length=254, unique=True, validators=[django.core.validators.EmailValidator()])),
                ('phone', models.CharField(help_text='10-digit phone number', max_length=10, validators=[django.core.validators.RegexValidator(message='Phone number must be exactly 10 digits.', regex='^\\d{10}$')])),
                ('position_applied', models.CharField(help_text='Job position the candidate applied for', max_length=255)),
                ('status', models.CharField(choices=[('Applied', 'Applied'), ('Interview', 'Interview'), ('Selected', 'Selected'), ('Rejected', 'Rejected')], default='Applied', help_text='Current status of the candidate application', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the candidate was added')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the candidate was last updated')),
            ],
            options={
                'verbose_name': 'Candidate',
                'verbose_name_plural': 'Candidates',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['email'], name='candidates__email_188e48_idx'), models.Index(fields=['status'], name='candidates__status_0f124f_idx'), models.Index(fields=['-created_at'], name='candidates__created_d94c2e_idx')],
            },
        ),
    ]
